#define _CRT_SECURE_NO_WARNINGS
#include "SDL/SDL.h"
#pragma comment(lib,"SDL\\sdl2.lib")
#pragma comment(lib,"SDL\\sdlmain2.lib")
#pragma comment(lib,"Winmm.lib")
#include <windows.h>
#include <stdio.h>
#include <math.h>
#include "Keyboard.h"
#include "RGB.h"
#include "Misc.h"
#include "Vector2.h"
#include "Cubic.h"
#include "Bitmap.h"
#include "BitmapFile.h"
#include "Draw.h"
#include "BitmapText.h"
#include "Animation.h"
#include "Video.h"
#include "player.h"
#include "BackgroundItem.h"
#include "Background.h"
#include "Player.h"
#include "Enemy.h"
#include "EnemyManager.h"
#include "Missile.h"
#include "MissileManager.h"
#include "GameElements.h"

